spring.application.name=lernello
# File uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# Storage
storage.path=./data/files
# JWT
jwt.secret=Zrjz1QyQmD6zXwT3J9bDk5b9kJ0g6e2K9vJ2f2sEbpM=
# Auth Cookies
app.auth.access-cookie-name=lernello_access
app.auth.refresh-cookie-name=lernello_refresh
# Prod should be true
app.auth.cookie-secure=false
app.auth.cookie-samesite=Lax
# TTLs
# Access-Token short-lived
app.auth.access-ttl=15m
# Remember=true
app.auth.refresh-long-ttl=30d
# Remember=false
app.auth.refresh-short-ttl=1d
# OTP
app.auth.code-ttl-minutes=10m
app.auth.resend-cooldown-seconds=30s
# JPA defaults
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
